name: Post Welcome Comment
on:
  pull-request:
    types: [opened]
  permissions:
    pull-requests: write
  jobs:
    build:
      name: Post Welcome Comment
      runs-on: ubuntu-latest
      
    
